AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Resources:
  getUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-user-info.handler
      Runtime: nodejs16.x
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref UserTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
