AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Resources:
          
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
  TempUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  SharedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sharedID
          AttributeType: S
      KeySchema:
        - AttributeName: sharedID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  getUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-user-info.handler
      Runtime: nodejs16.x
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref UserTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
      BuildMethod: esbuild

  registerPrepareFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/register-prepare.handler
      Runtime: nodejs16.x
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SharedTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TempUserTable
      Environment:
        Variables:
          SHARED_TABLE: !Ref SharedTable
          TEMP_USER_TABLE: !Ref TempUserTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /register
            Method: GET
    Metadata:
      BuildMethod: esbuild

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
